### ISSUE TITLE
RESTORATION - Stormwater: "FEATURE STATUS"

### ISSUE THREAD

**Issue by kerrymcmahon** [kerrymcmahon/Bay-Restoration-Executive-Viewer#1]
Because of the necessary join of EFF_BMP to NPDES.SWMFAC - the feature status is duplicated. Please remove FEATURE STATUS which is pulling from the field FEAT_STATUS in SWMFAC, and keep only STATUS which is pulling from the field STATUS. This is especially important for retrofits, where the TMDL status is "proposed" and the NPDES status would say existing.

![issue1](https://user-images.githubusercontent.com/9559830/37672637-4f7d12ae-2c66-11e8-8331-9dd0e9d57e6d.JPG)

**Comment by nswalls** [comment]
Oops, good catch. fixed
![image](https://user-images.githubusercontent.com/37626421/37843983-d1cd3fa8-2e9c-11e8-91d3-2335f64a3f42.png)
