### ISSUE TITLE
SITE SELECTION - Grass Swale: Contract Numbers

### ISSUE THREAD

**Issue by kerrymcmahon** [kerrymcmahon/Bay-Restoration-Executive-Viewer#2]
TMDL_CONTRACT_ID not used
PROJECT CONTRACT NUMBER - not even sure what field that is, but not used.
They are not present in the source data that I provided.
Remove both:

![issue2](https://user-images.githubusercontent.com/9559830/37673412-0be8f862-2c68-11e8-834d-58cfa5bda86e.JPG)

**Comment by nswalls** [comment]
something odd is going on - I dont show those fields at all
![image](https://user-images.githubusercontent.com/37626421/37843836-681c800a-2e9c-11e8-9bac-37995684053a.png)
![image](https://user-images.githubusercontent.com/37626421/37843877-86736d84-2e9c-11e8-8c0d-c4a4998e5c12.png)
(note we dont display the gis attribute fields)

**Comment by nswalls** [comment]
AHA! Maurice figured it out - your comments were regarding the Site Selection - Stormwater layer, not the Grass Swales. We have updated the SWM layer accordingly...also found a similar field enabled in Site Selection - Trees that we disabled.
